const Map<String, String> isoNations = {
  "AFG": "Afeganistão",
  "AGO": "Angola",
  "ALB": "Albânia",
  "AND": "Andorra",
  "ARE": "Emirados Árabes Unidos",
  "ARG": "Argentina",
  "ARM": "Arménia",
  "AUS": "Austrália",
  "AUT": "Áustria",
  "AZE": "Azerbaijão",
  "BEL": "Bélgica",
  "BEN": "Benim",
  "BFA": "Burkina Faso",
  "BGD": "Bangladesh",
  "BGR": "Bulgária",
  "BHR": "Bahrein",
  "BHS": "Bahamas",
  "BIH": "Bósnia e Herzegovina",
  "BLR": "Bielorrússia",
  "BLZ": "Belize",
  "BOL": "Bolívia",
  "BRA": "Brasil",
  "BRB": "Barbados",
  "CAN": "Canadá",
  "CHE": "Suíça",
  "CHL": "Chile",
  "CHN": "China",
  "CIV": "Costa do Marfim",
  "CMR": "Camarões",
  "COL": "Colômbia",
  "CPV": "Cabo Verde",
  "CRI": "Costa Rica",
  "CUB": "Cuba",
  "DEU": "Alemanha",
  "DNK": "Dinamarca",
  "DOM": "República Dominicana",
  "DZA": "Argélia",
  "ECU": "Equador",
  "EGY": "Egito",
  "ESP": "Espanha",
  "USA": "Estados Unidos",
  "FRA": "França",
  "GBR": "Reino Unido",
  "GRC": "Grécia",
  "GTM": "Guatemala",
  "GUY": "Guiana",
  "HKG": "Hong Kong",
  "HND": "Honduras",
  "HRV": "Croácia",
  "HUN": "Hungria",
  "IDN": "Indonésia",
  "IND": "Índia",
  "IRL": "Irlanda",
  "IRN": "Irão",
  "IRQ": "Iraque",
  "ISL": "Islândia",
  "ISR": "Israel",
  "ITA": "Itália",
  "JAM": "Jamaica",
  "JOR": "Jordânia",
  "JPN": "Japão",
  "KAZ": "Cazaquistão",
  "KEN": "Quénia",
  "KOR": "Coreia do Sul",
  "LBN": "Líbano",
  "MAR": "Marrocos",
  "MEX": "México",
  "MOZ": "Moçambique",
  "NGA": "Nigéria",
  "NOR": "Noruega",
  "NZL": "Nova Zelândia",
  "PAN": "Panamá",
  "PER": "Peru",
  "PHL": "Filipinas",
  "POL": "Polónia",
  "PRT": "Portugal",
  "PRY": "Paraguai",
  "RUS": "Rússia",
  "SAU": "Arábia Saudita",
  "SWE": "Suécia",
  "TUR": "Turquia",
  "UKR": "Ucrânia",
  "URY": "Uruguai",
  "VEN": "Venezuela",
  "ZAF": "África do Sul",
};
